services:
  - type: web
    name: projectsmanager
    env: python
    plan: free
    region: oregon

    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=$PORT

    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true

    build:
      image: python:3.12-slim  # 👈 Forces Python 3.12
