"""Change scope and tasks to one-to-many relationship

Revision ID: 3321c30191a5
Revises: 02b07cc9a9eb
Create Date: 2024-01-26 22:28:38.432734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3321c30191a5'
down_revision = '02b07cc9a9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_scope_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_scope_association',
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('scope_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scope.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'scope_id')
    )
    # ### end Alembic commands ###
