"""Added scope_id to task

Revision ID: f4ff182a1ad5
Revises: 3321c30191a5
Create Date: 2024-01-26 23:02:59.900052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ff182a1ad5'
down_revision = '3321c30191a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_scope_id', 'scope', ['scope_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scope_id', type_='foreignkey')
        batch_op.drop_column('scope_id')

    # ### end Alembic commands ###
